

variable "server_port" {
description = "The port the server will use for HTTP requests"
type = number
default = 80
}

variable "generated_key_name" {
  type        = string
  default     = "UPandRunningKey"
  description = "Key-pair generated by Terraform"
}
